import type { RtoLocation } from "./types";

/**
 * State codes are complete. Office names are a curated subset covering the
 * highest-volume RTOs — lookups outside it degrade to "RTO <code>" rather than
 * guessing. To fill in the rest, merge entries from the public dataset at
 * https://en.wikipedia.org/wiki/List_of_Regional_Transport_Office_districts_in_India
 * into RTO_OFFICES below; nothing else needs to change.
 */

export const STATE_NAMES: Record<string, string> = {
  AN: "Andaman & Nicobar Islands",
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CG: "Chhattisgarh",
  CH: "Chandigarh",
  DD: "Dadra & Nagar Haveli and Daman & Diu",
  DL: "Delhi",
  DN: "Dadra & Nagar Haveli",
  GA: "Goa",
  GJ: "Gujarat",
  HP: "Himachal Pradesh",
  HR: "Haryana",
  JH: "Jharkhand",
  JK: "Jammu & Kashmir",
  KA: "Karnataka",
  KL: "Kerala",
  LA: "Ladakh",
  LD: "Lakshadweep",
  MH: "Maharashtra",
  ML: "Meghalaya",
  MN: "Manipur",
  MP: "Madhya Pradesh",
  MZ: "Mizoram",
  NL: "Nagaland",
  OD: "Odisha",
  OR: "Odisha",
  PB: "Punjab",
  PY: "Puducherry",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TG: "Telangana",
  TN: "Tamil Nadu",
  TR: "Tripura",
  TS: "Telangana",
  UA: "Uttarakhand",
  UK: "Uttarakhand",
  UP: "Uttar Pradesh",
  WB: "West Bengal",
};

/** Codes retired in favour of a newer one, kept so old plates still resolve. */
export const SUPERSEDED_STATE_CODES: Record<string, string> = {
  OR: "OD",
  UA: "UK",
  TS: "TG",
};

const RTO_OFFICES: Record<string, Record<string, string>> = {
  MH: {
    "01": "Mumbai (South) — Tardeo",
    "02": "Mumbai (West) — Andheri",
    "03": "Mumbai (East) — Wadala",
    "04": "Thane",
    "05": "Kalyan",
    "06": "Raigad — Alibag",
    "07": "Sindhudurg",
    "08": "Ratnagiri",
    "09": "Kolhapur",
    "10": "Sangli",
    "11": "Satara",
    "12": "Pune",
    "13": "Solapur",
    "14": "Pimpri-Chinchwad",
    "15": "Nashik",
    "16": "Shrirampur",
    "17": "Ahmednagar",
    "18": "Dhule",
    "19": "Jalgaon",
    "20": "Chhatrapati Sambhajinagar (Aurangabad)",
    "21": "Jalna",
    "22": "Parbhani",
    "23": "Beed",
    "24": "Latur",
    "25": "Dharashiv (Osmanabad)",
    "26": "Nanded",
    "27": "Amravati",
    "28": "Buldhana",
    "29": "Yavatmal",
    "30": "Akola",
    "31": "Nagpur",
    "32": "Wardha",
    "33": "Gadchiroli",
    "34": "Chandrapur",
    "35": "Gondia",
    "36": "Bhandara",
    "37": "Washim",
    "38": "Hingoli",
    "39": "Nandurbar",
    "40": "Nagpur (Rural)",
    "41": "Malegaon",
    "42": "Baramati",
    "43": "Navi Mumbai — Vashi",
    "46": "Panvel",
    "47": "Mumbai (North) — Borivali",
    "48": "Vasai-Virar",
    "50": "Karad",
  },
  DL: {
    "01": "Delhi — Mall Road",
    "02": "Delhi — Rajpura Road",
    "03": "Delhi — Sheikh Sarai",
    "04": "Delhi — Janakpuri",
    "05": "Delhi — Loni Road",
    "06": "Delhi — Sarai Kale Khan",
    "07": "Delhi — Mayur Vihar",
    "08": "Delhi — Wazirpur",
    "09": "Delhi — Dwarka",
    "10": "Delhi — Raja Garden",
    "11": "Delhi — Rohini",
    "12": "Delhi — Vasant Vihar",
    "13": "Delhi — Surajmal Vihar",
  },
  KA: {
    "01": "Bengaluru Central — Koramangala",
    "02": "Bengaluru West — Rajajinagar",
    "03": "Bengaluru East — Indiranagar",
    "04": "Bengaluru North — Yeshwanthpur",
    "05": "Bengaluru South — Jayanagar",
    "06": "Tumakuru",
    "09": "Mysuru",
    "11": "Mandya",
    "13": "Hassan",
    "14": "Shivamogga",
    "16": "Chitradurga",
    "17": "Davanagere",
    "19": "Mangaluru",
    "20": "Udupi",
    "22": "Belagavi",
    "25": "Dharwad — Hubballi",
    "28": "Vijayapura",
    "30": "Karwar",
    "32": "Kalaburagi",
    "34": "Ballari",
    "36": "Raichur",
    "38": "Bidar",
    "41": "Bengaluru North — Jnanabharathi",
    "51": "Bengaluru South — Electronic City",
  },
  TN: {
    "01": "Chennai Central",
    "02": "Chennai North East",
    "03": "Chennai West",
    "04": "Chennai North",
    "05": "Chennai North West",
    "07": "Chennai South",
    "09": "Chennai South East",
    "10": "Chennai East",
    "11": "Kanchipuram",
    "20": "Chengalpattu",
    "22": "Chennai South West",
    "23": "Vellore",
    "33": "Salem",
    "37": "Coimbatore South",
    "38": "Coimbatore North",
    "43": "Nilgiris — Ooty",
    "45": "Tiruchirappalli",
    "58": "Madurai South",
    "59": "Madurai North",
    "67": "Thanjavur",
    "69": "Thoothukudi",
    "72": "Tirunelveli",
    "74": "Nagercoil",
  },
  TG: {
    "07": "Hyderabad North West — Kukatpally",
    "08": "Rangareddy — Ibrahimpatnam",
    "09": "Hyderabad Central — Khairatabad",
    "10": "Hyderabad East — Malakpet",
    "11": "Hyderabad South — Attapur",
    "12": "Hyderabad North — Secunderabad",
    "13": "Hyderabad West — Mehdipatnam",
    "14": "Hyderabad — Medchal",
    "15": "Medak",
    "16": "Nizamabad",
    "36": "Warangal",
  },
  // AP codes below ~26 were issued before the Telangana split and may sit on
  // vehicles now registered there; only unambiguous AP districts are listed.
  AP: {
    "05": "Srikakulam",
    "07": "Visakhapatnam",
    "16": "Vijayawada",
    "21": "Guntur",
    "26": "Nellore",
    "31": "Kurnool",
    "37": "Tirupati",
    "39": "Kadapa",
  },
  GJ: {
    "01": "Ahmedabad",
    "02": "Mehsana",
    "03": "Rajkot",
    "05": "Surat",
    "06": "Vadodara",
    "07": "Nadiad",
    "09": "Anand",
    "10": "Jamnagar",
    "12": "Kachchh — Bhuj",
    "15": "Valsad",
    "16": "Bharuch",
    "18": "Gandhinagar",
    "21": "Navsari",
    "27": "Ahmedabad East — Vastral",
  },
  HR: {
    "01": "Ambala",
    "05": "Karnal",
    "06": "Panipat",
    "10": "Sonipat",
    "12": "Faridabad",
    "20": "Hisar",
    "26": "Gurugram (West)",
    "29": "Faridabad — Ballabgarh",
    "36": "Rewari",
    "51": "Faridabad",
    "55": "Gurugram (Commercial)",
    "72": "Gurugram (South)",
  },
  UP: {
    "14": "Ghaziabad",
    "16": "Noida — Gautam Buddha Nagar",
    "32": "Lucknow",
    "33": "Lakhimpur Kheri",
    "50": "Gorakhpur",
    "65": "Varanasi",
    "70": "Prayagraj (Allahabad)",
    "78": "Kanpur",
    "80": "Agra",
    "85": "Mathura",
  },
  RJ: {
    "14": "Jaipur",
    "19": "Jodhpur",
    "20": "Kota",
    "27": "Udaipur",
    "45": "Jaipur South",
  },
  WB: {
    "01": "Kolkata — Beltala (Alipore)",
    "02": "Kolkata — Beltala",
    "06": "Kolkata — Kasba",
    "07": "Kolkata — Kasba",
    "19": "Barasat — North 24 Parganas",
    "20": "Barasat",
    "23": "Barrackpore",
    "24": "Barrackpore",
    "26": "Howrah",
    "34": "Bardhaman",
    "37": "Durgapur — Asansol",
    "62": "Siliguri — Darjeeling",
  },
  // Kerala allocates 01-14 district-wise, in district order
  KL: {
    "01": "Thiruvananthapuram",
    "02": "Kollam",
    "03": "Pathanamthitta",
    "04": "Alappuzha",
    "05": "Kottayam",
    "06": "Idukki",
    "07": "Ernakulam",
    "08": "Thrissur",
    "09": "Palakkad",
    "10": "Malappuram",
    "11": "Kozhikode",
    "12": "Wayanad",
    "13": "Kannur",
    "14": "Kasaragod",
  },
  PB: {
    "01": "Chandigarh (Punjab)",
    "02": "Amritsar",
    "08": "Jalandhar",
    "10": "Ludhiana",
    "11": "Patiala",
    "65": "Mohali",
  },
  MP: {
    "04": "Bhopal",
    "07": "Gwalior",
    "09": "Indore",
    "20": "Jabalpur",
    "33": "Ujjain",
  },
  GA: {
    "01": "Panaji",
    "02": "Margao",
    "03": "Mapusa",
    "05": "Ponda",
    "06": "Vasco da Gama",
    "07": "Bicholim",
    "08": "Quepem",
  },
  CH: { "01": "Chandigarh" },
  PY: { "01": "Puducherry", "02": "Karaikal", "03": "Mahe", "04": "Yanam" },
};

export function isKnownStateCode(code: string): boolean {
  return code.toUpperCase() in STATE_NAMES;
}

/** Resolve state + office. Office falls back to a generic label when unmapped. */
export function lookupRto(
  stateCode: string,
  rtoCode?: string,
): RtoLocation | undefined {
  const code = stateCode.toUpperCase();
  const stateName = STATE_NAMES[code];
  if (!stateName) return undefined;

  if (!rtoCode) {
    return { stateCode: code, stateName, officeKnown: false };
  }

  const padded = rtoCode.padStart(2, "0");
  const current = SUPERSEDED_STATE_CODES[code] ?? code;
  const office =
    RTO_OFFICES[code]?.[padded] ?? RTO_OFFICES[current]?.[padded];

  return {
    stateCode: code,
    stateName,
    office: office || `RTO ${padded}`,
    officeKnown: Boolean(office),
  };
}
