import type { ClaimDetails } from "./constants";

export function claimReceiptFileName(claimId: string): string {
  const safeId = claimId.trim().toUpperCase().replace(/[^A-Z0-9-]/g, "-");
  return `${safeId || "claim"}-claim-receipt.pdf`;
}

function pdfSafeAmount(value: string): string {
  return value.replace("₹", "INR ").replace(/\s+/g, " ").trim();
}

export function claimReceiptRows(claim: ClaimDetails): Array<[string, string]> {
  return [
    ["Claim ID", claim.id],
    ["Merchant", claim.vendor],
    ["Category", claim.category],
    ["Amount", pdfSafeAmount(claim.amount)],
    ["Submitted", claim.submittedAt],
    ["Current status", claim.currentStatus],
  ];
}

export async function downloadClaimReceipt(claim: ClaimDetails): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const document = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const rows = claimReceiptRows(claim);

  document.setFillColor(242, 249, 245);
  document.rect(0, 0, 210, 42, "F");
  document.setTextColor(18, 63, 54);
  document.setFont("helvetica", "bold");
  document.setFontSize(20);
  document.text("Claim receipt", 18, 22);
  document.setFontSize(10);
  document.setFont("helvetica", "normal");
  document.text(`Generated ${new Date().toLocaleString("en-IN")}`, 18, 31);

  let y = 56;
  rows.forEach(([label, value]) => {
    document.setTextColor(96, 117, 110);
    document.setFont("helvetica", "normal");
    document.setFontSize(9);
    document.text(label.toUpperCase(), 18, y);
    document.setTextColor(18, 63, 54);
    document.setFont("helvetica", "bold");
    document.setFontSize(12);
    document.text(value || "-", 18, y + 7, { maxWidth: 174 });
    document.setDrawColor(226, 235, 230);
    document.line(18, y + 13, 192, y + 13);
    y += 24;
  });

  document.setTextColor(96, 117, 110);
  document.setFont("helvetica", "normal");
  document.setFontSize(9);
  document.text(
    "This receipt was generated by the Employee Benefits demo.",
    18,
    280,
  );
  document.save(claimReceiptFileName(claim.id));
}
